# Generated by Django 5.0.1 on 2024-01-10 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
