# Generated by Django 5.0.1 on 2024-01-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verification_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
