name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change to frontend directory
      run: cd frontend
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run Playwright Tests
      run: npx playwright test
